databases:
  - name: sales-db
    plan: free
    databaseName: salesdb

services:
  - type: web
    name: sales-dashboard
    runtime: image
    plan: free
    image:
      url: docker.io/paraje11/sales-dashboard:latest
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: sales-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: sales-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: sales-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: sales-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: sales-db
          property: password
